### PR TITLE
Change detail level adaptively

### LINKED ISSUE #2: Adaptive detail level
As you zoom in farther and farther, you start to lose resolution on the edge of the stable region.  This can be fixed by increasing the value of `n` passed to `generate_mandelbrot`.
Here's what it looks like with the default `n=100`.
image
And here's a similar view with `n=1000`, but of course, this is much slower.
Screenshot 2023-04-25 at 14 31 01
With a bit of experimentation, you should be able to determine a logarithmic relationship between the visible scale and the number of iterations.  For reference, in the initial view the vertical range is 3, and n=100 is sufficient;  in my example, when the vertical range is about 0.003, n=1000 seems to be more than sufficient.

### PR DESCRIPTION
**Pull request by kuromusha**
This PR is to enable #2.

`n` is calculated by `log10(3 / range) * 30 + 100`.
adaptive_detail_level

### CODE REVIEW

**Review by timdiller — APPROVED** [review]
Looks good.  At extreme zoom factors, the level of detail seems insufficient, but getting that right is probably its own research project.  And I imagine that plenty of others have researched the right number of iterations for the mandelbrot escape function.
I don't know for sure, but I suspect that you might get a bit better performance if you don't recreate the `Plot` object each time.  Rather, keep a reference to the `ArrayPlotData` instance and use its `set_data(array_name, new_data)` method to update the data.  Your current implementation is reasonably performant, but that might help you get better scrolling.
But for now, it looks good.

**Comment by kuromusha** [comment]
@timdiller 
Thank you for your comment.

Regarding the detail level, I miscalculated it. `n` should have been calculated by `log10(3 / range) * 300 + 100` for `range=0.0003` and `n=1000`. I modified the calculation. https://github.com/kuromusha/mandelbrot-chaco/pull/4/commits/d2baa88beaf0885d2c0da04f9c705e69c2044da4 It looks better than before. But it takes more time for extreme zoom factors and the calculation formula can be improved as you mentioned. (They are other problems, though.)

Regarding the drawing performance, I modified the way of updating the plot as you advised. https://github.com/kuromusha/mandelbrot-chaco/pull/4/commits/dd04858dd7dcc988db12fde5ae7cf88a48bb73cc The performance became a little better. Thank you very much for your advice!

**Comment by timdiller** [comment]
@kuromusha Looks good to me.  See [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for help on how to link a pull request to an issue.  You can explicitly make the link by editing the PR through the Github interface, or you can include the words " Closes #2 " in the description to trigger it implicitly.

**Comment by kuromusha** [comment]
@timdiller 
Thank you. I linked this PR with the Issue #2. And I merge this.

**Pull request merged**
